dist: focal
language: c++
os: linux

cache: ccache

env:
  - LLVM_VERSION=11

addons:
  apt:
    sources:
      - sourceline: ppa:ubuntu-toolchain-r/test
      - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main'
        key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
    packages:
      - clang-11
      - libc6=2.31-0ubuntu9.2
      - libc6-dev=2.31-0ubuntu9.2
      - llvm-11-dev
      - lld-11

script:
  - ./build.sh

before_deploy:
  - ./before-deploy.sh

deploy:
  provider: releases
  api_key:
    secure: "Ci7xuVIdOx9sYAE2Hyz4AfaZ0VqPwzMB9wMB+QDFgFg+WUAvTfPZzvyW/CIEvxpefb1NbixeFvxsI8AZ4oLfht63wVSzySk4gNECxvTBgaQJiweKDXFQiiLe7qrUR4uGg3TY75ackLTAQxn8x5sl5M+wt+0L5PxIyC1wW1DXuETfc+/xNg1vW71QCgXzzAGgXCpfHwxrlRIsXXhujpitpeeWEJoci6H5M94Um57fBV+G/Cuyn+2JcnNGuYJ+ukOpxZht6vr3GyoZW22rhE4Bbr7NTN4rLY1N4BBHfXIG4iVPf0nE7tJ7RuNbVY6gf6/7CV5yP/psS31CHsoETwc0uGfMabot6VsLTxTUFKKAEkyOucG/H+6tV8pCxitk09bO+z+j7GH7bsEFxTnoeGO7/Gq29jPbjwVxDnLbW8PIYqql8TA+/isVpAMCbwPN02qhDndkB2rjsmDNiwrIdMfkLWgWhwNuxoqIr6iK94ksFsIsB4RIFx9GbyH70kiVaalnd/KQLQzsDUn5qgMah6sLlC2FbRAZOR+tC67AUNgckgGPwhkYPJq6uINFMUEh+6CSclYE0LhZyH6xnIEq/oWLRBRQRXeEN43GiCh7lKAzNBvuAUGEsn313egt03S38x5ss93tmi1QbqxtqG8erHqdDnNjSdKKeM6r5graiEWPQ8s="
  file: clang-tidy-plugin-support-$TRAVIS_TAG.tar.xz
  skip_cleanup: true
  on:
    tags: true
    repo: jbytheway/clang-tidy-plugin-support
