dist: xenial
language: c++
os: linux

cache: ccache

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-8
    packages:
      - clang-8
      - llvm-8-dev
      - lld-8

script:
  - ./build.sh

deploy:
  provider: releases
  api_key:
    secure: LGEdJvjus65RepoNuCEq5XPNaxBAFDfIXmTnuUsH3uMzi0/VTYoz1j04/xJb9uYTnLiZmSSJZVZCR7DwN0EySGaMP8Qhbs73wN5Igjs5rmNi5/ttsJDPhZNbku5cK9IL8aS15xVRBLDqsmj7eypSw+dUJCQhlxNb2//lqm1hk1Nrgnek4f1ojQL5GqPVtwBtWMFPOO+/OAV3qh/LpGRBWqQZo6K4Dhgf3rKrLA9hw8RKctgSRfeWJvTjULWBQM5XGCr2ios9KL0ngcusC9QchTsETHPjT4l10jvVuMhthQiPcFgOtokqLd0v6PXbGehumzRkjtHWqAQwGMkDWJR8gmO95HPG3wJ+2/qp9du1z1WD+KTUwW26QiuQ1jwrD1FIo4D2xokFsSW1B0GW8sSwaHwbpkMZRlAy5zAS9Fx9TiXITZtCWDdhtfFEWssHt/ZwzscdXsakxFs82P8rpom9c/dT1u3wAkj+7HBr5YKtm57IfZ6iS/bwARd6BHjXYF/4FX8gilQ7D53V5V7mUptnNVvZ+dSZxNLhu19gBDW7RiH6QFwD+OPO+vhdIx4o9mvKqTc4zXtykHr0g2u2ZY+VL+8wzBVL5Ixd1yJj49WklZs4BCQmPxEKTeqJzYkpVozMlpFYRjZYecdVfXID9HOdOVsxS8GieV1hDHnwJGsQaHk=
  file: build/bin/clang-tidy
  on:
    repo: jbytheway/clang-tidy-plugin-support
