name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      LLVM_VERSION: 12
    steps:
    - name: checkout repository
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: install dependencies
      run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | \
            sudo apt-key add -
          sudo apt-add-repository \
            "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main"
          sudo apt-get update
          sudo apt-get install clang-12 libclang-12-dev llvm-12-dev \
            llvm-12-tools lld-12 ccache
    - name: Get Date
      id: get-date
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%Y%m%d%H%M")"
      shell: bash
    - name: ccache cache files
      if: runner.os == 'Linux'
      uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ccache-linux-${{ matrix.config.name }}-${{ steps.get-date.outputs.date }}
        restore-keys: |
          ccache-linux-${{ matrix.config.name }}-
    - name: build
      run: bash ./build.sh
